trigger: none

pool:
  name: Default
  demands:
    - agent.name -equals linux-agent

stages:
  - stage: Build
    displayName: 'Build Android APK'
    jobs:
      - job: Build
        timeoutInMinutes: 120
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '22.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g yarn
              yarn --version
            displayName: 'Install Yarn'

          - script: |
              yarn install --ignore-engines
            displayName: 'Yarn Install Root'

          - script: |
              cd package
              yarn install --ignore-engines
            displayName: 'Yarn Install Package'

          - script: |
              cd package/native-package
              yarn install --ignore-engines
            displayName: 'Yarn Install Native Package'

          - script: |
              cd examples/SampleApp
              yarn install --ignore-engines
            displayName: 'Yarn Install SampleApp'

          - script: |
              export ANDROID_HOME=$HOME/android-sdk
              export
